export const surveyConfig = {
  buckets: [
    {
      id: "already_done",
      label: "Already secured",
      description: "I already have an internship or job lined up",
      icon: "CheckCircle",
      stages: ["already_secured"],
    },
    {
      id: "getting_started",
      label: "Getting started",
      description: "Figuring out what I want and where to begin",
      icon: "Compass",
      stages: ["awareness", "direction"],
    },
    {
      id: "applying",
      label: "Applying",
      description: "Searching, building materials, and submitting applications",
      icon: "Send",
      stages: ["search", "materials", "applying"],
    },
    {
      id: "interviewing",
      label: "Interviewing",
      description: "Preparing for and going through interviews",
      icon: "MessageSquare",
      stages: ["screening", "live_interviews"],
    },
    {
      id: "getting_offer",
      label: "Getting the offer",
      description: "Navigating offers, decisions, and next steps",
      icon: "Trophy",
      stages: ["offers", "waiting"],
    },
  ],

  pipelineStages: [
    {
      id: "already_secured",
      label: "I already have an internship or job lined up",
      shortLabel: "Secured",
      icon: "CheckCircle",
      drilldownQuestion: "Looking back, what was the most challenging part of the process?",
      drilldownBuckets: [
        {
          id: "early_challenges",
          label: "Early-stage challenges",
          description: "Direction and finding opportunities",
          icon: "Compass",
          options: ["retro_direction", "retro_finding", "retro_materials"],
        },
        {
          id: "late_challenges",
          label: "Late-stage challenges",
          description: "Interviews, offers, and hearing back",
          icon: "MessageSquare",
          options: ["retro_hearing_back", "retro_interviews", "retro_offers"],
        },
      ],
      drilldownOptions: [
        { id: "retro_direction", label: "Figuring out what kind of role I actually wanted", icon: "Compass" },
        { id: "retro_finding", label: "Finding the right opportunities to apply to", icon: "Search" },
        { id: "retro_materials", label: "Getting my resume and materials strong enough", icon: "FileText" },
        { id: "retro_hearing_back", label: "Hearing back after submitting applications", icon: "Inbox" },
        { id: "retro_interviews", label: "Performing well in interviews", icon: "MessageSquare" },
        { id: "retro_offers", label: "Deciding between options", icon: "Scale" },
      ],
      resourceNudge: "Congrats on locking it in! Your response helps us understand what the hardest parts of the search really are, so we can better support students who are still looking.",
    },
    {
      id: "awareness",
      label: "I didn't realize I needed to be thinking about internships yet",
      shortLabel: "Awareness",
      icon: "Lightbulb",
      drilldownQuestion: "What's closest to your situation?",
      drilldownBuckets: [
        {
          id: "didnt_know",
          label: "I didn't know",
          description: "I wasn't aware this mattered yet",
          icon: "AlertCircle",
          options: ["didnt_know_important", "too_early"],
        },
        {
          id: "focused_elsewhere",
          label: "Focused on other things",
          description: "I had other priorities",
          icon: "BookOpen",
          options: ["focused_grades", "no_pressure"],
        },
      ],
      drilldownOptions: [
        { id: "didnt_know_important", label: "Nobody told me internships were this important for getting hired after graduation", icon: "AlertCircle" },
        { id: "too_early", label: "I figured internships were a junior or senior year thing", icon: "Clock" },
        { id: "focused_grades", label: "I've been focused on getting good grades and assumed that would be enough", icon: "BookOpen" },
        { id: "no_pressure", label: "No one around me is doing internships yet so I didn't feel the urgency", icon: "Users" },
      ],
      resourceNudge: "You're not behind. But starting now gives you a real edge. The career center can help you figure out the first step in a 15-minute meeting.",
    },
    {
      id: "direction",
      label: "I want an internship but I have no idea what kind",
      shortLabel: "Direction",
      icon: "Compass",
      drilldownQuestion: "What makes picking a direction hard?",
      drilldownBuckets: [
        {
          id: "too_many_choices",
          label: "Too many choices",
          description: "Overwhelmed by options",
          icon: "GitBranch",
          options: ["too_many_options", "dont_know_roles"],
        },
        {
          id: "not_enough_info",
          label: "Not enough information",
          description: "Need more exposure and clarity",
          icon: "Eye",
          options: ["interests_dont_match", "no_exposure"],
        },
      ],
      drilldownOptions: [
        { id: "too_many_options", label: "There are so many options I feel paralyzed trying to choose", icon: "GitBranch" },
        { id: "dont_know_roles", label: "I know my major but I don't know what actual job roles exist for it", icon: "Map" },
        { id: "interests_dont_match", label: "What I'm interested in doesn't seem to connect to available internships", icon: "Unlink" },
        { id: "no_exposure", label: "I haven't had enough real-world exposure to know what I'd actually enjoy", icon: "Eye" },
      ],
      resourceNudge: "This is more common than you think. The career center runs industry exploration sessions that take 30 minutes and help you narrow it down fast.",
    },
    {
      id: "search",
      label: "I know what I want but I can't find the right opportunities",
      shortLabel: "Search",
      icon: "Search",
      drilldownQuestion: "What's making the search hard?",
      drilldownBuckets: [
        {
          id: "cant_find",
          label: "Can't find opportunities",
          description: "Not sure where or what to search",
          icon: "Globe",
          options: ["dont_know_where", "nothing_for_major"],
        },
        {
          id: "barriers",
          label: "Facing barriers",
          description: "Experience or connections blocking me",
          icon: "Lock",
          options: ["all_require_experience", "no_connections"],
        },
      ],
      drilldownOptions: [
        { id: "dont_know_where", label: "I don't know where to look beyond Handshake and LinkedIn", icon: "Globe" },
        { id: "nothing_for_major", label: "I search but the results don't match my major or interests", icon: "FilterX" },
        { id: "all_require_experience", label: "Every posting I find wants prior experience I don't have", icon: "Lock" },
        { id: "no_connections", label: "I don't have any professional connections or know anyone in the industry", icon: "UserX" },
      ],
      resourceNudge: "The career center maintains employer lists by major that aren't on Handshake. Book a quick meeting to get access.",
    },
    {
      id: "materials",
      label: "My resume and materials aren't application ready",
      shortLabel: "Materials",
      icon: "FileText",
      drilldownQuestion: "What specifically isn't ready?",
      drilldownBuckets: [
        {
          id: "resume_issues",
          label: "Resume needs work",
          description: "Content or quality concerns",
          icon: "FileText",
          options: ["empty_resume", "weak_resume"],
        },
        {
          id: "other_materials",
          label: "Other application materials",
          description: "Cover letters and tailoring",
          icon: "PenLine",
          options: ["cover_letter", "cant_tailor"],
        },
      ],
      drilldownOptions: [
        { id: "empty_resume", label: "I don't have relevant experience to put on my resume", icon: "FileX" },
        { id: "weak_resume", label: "I have a resume but I don't think it stands out", icon: "FileMinus" },
        { id: "cover_letter", label: "I don't know how to write a cover letter that doesn't sound generic", icon: "PenLine" },
        { id: "cant_tailor", label: "I struggle to customize my application for each company", icon: "Copy" },
      ],
      resourceNudge: "Resume clinics run weekly with no appointment needed. Bring what you have and walk out with something stronger.",
    },
    {
      id: "applying",
      label: "I'm submitting applications but not hearing back",
      shortLabel: "Applying",
      icon: "Inbox",
      drilldownQuestion: "What best describes your situation?",
      drilldownBuckets: [
        {
          id: "volume_problem",
          label: "Volume issue",
          description: "Not applying enough or hearing nothing",
          icon: "ArrowUp",
          options: ["few_apps", "many_apps_silence"],
        },
        {
          id: "timing_filtering",
          label: "Timing or filtering issues",
          description: "Getting filtered out or missing windows",
          icon: "CalendarX",
          options: ["auto_rejections", "missing_deadlines"],
        },
      ],
      drilldownOptions: [
        { id: "few_apps", label: "I've only applied to a handful of places and need to do more", icon: "ArrowUp" },
        { id: "many_apps_silence", label: "I've applied to 10+ internships and heard nothing back", icon: "Inbox" },
        { id: "auto_rejections", label: "I keep getting instant rejections before anyone even looks at my application", icon: "XCircle" },
        { id: "missing_deadlines", label: "By the time I find postings, the deadlines have already passed", icon: "CalendarX" },
      ],
      resourceNudge: "If you're applying and not hearing back, it's usually a targeting or materials issue, not a you issue. A 15-minute application review can diagnose it.",
    },
    {
      id: "screening",
      label: "I'm getting screening or HireVue invites but not advancing",
      shortLabel: "Screening",
      icon: "Video",
      drilldownQuestion: "What's happening with your screening interviews?",
      drilldownBuckets: [
        {
          id: "video_interviews",
          label: "Video interviews",
          description: "HireVue and recorded screenings",
          icon: "Video",
          options: ["hirevue_ghosted", "hirevue_prep"],
        },
        {
          id: "other_screening",
          label: "Other screening steps",
          description: "Phone screens and assessments",
          icon: "PhoneOff",
          options: ["phone_screen_stuck", "assessment_filtered"],
        },
      ],
      drilldownOptions: [
        { id: "hirevue_ghosted", label: "I complete HireVue or video interviews but never hear back", icon: "VideoOff" },
        { id: "phone_screen_stuck", label: "I get phone screens but can't seem to advance to the next round", icon: "PhoneOff" },
        { id: "hirevue_prep", label: "I don't know how to prepare for recorded video interviews", icon: "HelpCircle" },
        { id: "assessment_filtered", label: "I keep getting screened out by automated assessments or tests", icon: "XCircle" },
      ],
      resourceNudge: "Video interviews feel unnatural for everyone. The career center has HireVue practice tools and tips that make a real difference.",
    },
    {
      id: "live_interviews",
      label: "I'm doing live interviews but not getting offers",
      shortLabel: "Live Int",
      icon: "MessageSquare",
      drilldownQuestion: "Where in live interviews are things breaking down?",
      drilldownBuckets: [
        {
          id: "performance",
          label: "Performance under pressure",
          description: "Nerves and behavioral questions",
          icon: "HeartPulse",
          options: ["nerves", "behavioral_weak"],
        },
        {
          id: "technical_results",
          label: "Technical or final rounds",
          description: "Case studies and late-stage rejections",
          icon: "Code",
          options: ["technical_weak", "final_round_rejected"],
        },
      ],
      drilldownOptions: [
        { id: "nerves", label: "I get nervous and can't communicate clearly under pressure", icon: "HeartPulse" },
        { id: "behavioral_weak", label: "I struggle with behavioral questions like 'tell me about a time...'", icon: "MessageCircle" },
        { id: "technical_weak", label: "I can't handle case studies or technical questions well", icon: "Code" },
        { id: "final_round_rejected", label: "I make it to final rounds but keep getting rejected at the end", icon: "ArrowRight" },
      ],
      resourceNudge: "Mock interviews happen every week. Students who do even one practice run perform significantly better in the real thing.",
    },
    {
      id: "offers",
      label: "I have an offer but I'm not sure it's the right one",
      shortLabel: "Offers",
      icon: "Scale",
      drilldownQuestion: "What's making the decision hard?",
      drilldownBuckets: [
        {
          id: "comparing_options",
          label: "Evaluating options",
          description: "Comparing offers or not feeling excited",
          icon: "Scale",
          options: ["comparing", "not_excited"],
        },
        {
          id: "pressure_logistics",
          label: "Pressure and logistics",
          description: "Deadlines, location, or compensation",
          icon: "Timer",
          options: ["pressure_to_decide", "location_comp"],
        },
      ],
      drilldownOptions: [
        { id: "comparing", label: "I'm comparing multiple offers and don't know how to evaluate the tradeoffs", icon: "Scale" },
        { id: "not_excited", label: "I have one offer but it's not what I was hoping for", icon: "Meh" },
        { id: "pressure_to_decide", label: "They're pressuring me to decide fast and I need more time", icon: "Timer" },
        { id: "location_comp", label: "The location or compensation isn't what I expected", icon: "MapPin" },
      ],
      resourceNudge: "Don't decide alone. A career advisor can walk you through an offer evaluation in one meeting. Book one before your deadline.",
    },
    {
      id: "waiting",
      label: "I'm waiting to hear back and don't know what to do in the meantime",
      shortLabel: "Waiting",
      icon: "Clock",
      drilldownQuestion: "What's making the waiting period hard?",
      drilldownBuckets: [
        {
          id: "no_response",
          label: "No response",
          description: "Ghosted or stalled processes",
          icon: "Clock",
          options: ["ghosted_after_interview", "stalled_process"],
        },
        {
          id: "uncertainty",
          label: "Uncertainty",
          description: "Not sure what to do while waiting",
          icon: "HelpCircle",
          options: ["unsure_keep_applying", "anxiety"],
        },
      ],
      drilldownOptions: [
        { id: "ghosted_after_interview", label: "I interviewed weeks ago and haven't heard anything", icon: "Clock" },
        { id: "unsure_keep_applying", label: "I don't know if I should keep applying while I wait", icon: "HelpCircle" },
        { id: "stalled_process", label: "I've been told I'm 'in consideration' but nothing moves forward", icon: "Pause" },
        { id: "anxiety", label: "I'm anxious and it's affecting my ability to focus on other things", icon: "CloudRain" },
      ],
      resourceNudge: "The waiting is the hardest part. Keep applying while you wait. A career advisor can help you manage the process so you're not putting all your eggs in one basket.",
    },
  ],

  followUpQuestions: [
    {
      id: "follow_up_secured_1",
      question: "What single resource or experience helped you the most?",
      onlyForStage: "already_secured",
      buckets: [
        {
          id: "converted_or_center",
          label: "Structured support",
          description: "Internship conversion or career center",
          icon: "Repeat",
          options: ["secured_internship_converted", "secured_career_center"],
        },
        {
          id: "self_or_network",
          label: "Self-directed or connections",
          description: "Figured it out independently",
          icon: "Target",
          options: ["secured_personal_network", "secured_self_directed"],
        },
      ],
      options: [
        { id: "secured_internship_converted", label: "A previous internship or experience converted into an offer", icon: "Repeat" },
        { id: "secured_career_center", label: "Working with a career advisor or attending a career event", icon: "Users" },
        { id: "secured_personal_network", label: "A personal connection or referral", icon: "Link" },
        { id: "secured_self_directed", label: "I found it on my own through online applications", icon: "Target" },
        { id: "secured_professor", label: "A professor or class connection", icon: "GraduationCap" },
      ],
    },
    {
      id: "follow_up_1",
      question: "How many internships have you applied to this year?",
      buckets: [
        {
          id: "getting_started_apps",
          label: "Just getting started",
          description: "Haven't applied much yet",
          icon: "Circle",
          options: ["applied_0", "applied_1_5"],
        },
        {
          id: "been_at_it",
          label: "Been at it",
          description: "Applied to several or many",
          icon: "ChevronsUp",
          options: ["applied_6_15", "applied_15_plus"],
        },
      ],
      options: [
        { id: "applied_0", label: "None yet", icon: "Circle" },
        { id: "applied_1_5", label: "1 to 5", icon: "ArrowUp" },
        { id: "applied_6_15", label: "6 to 15", icon: "ArrowUpRight" },
        { id: "applied_15_plus", label: "More than 15", icon: "ChevronsUp" },
      ],
    },
    {
      id: "follow_up_2",
      question: "When did you start actively looking for an internship?",
      buckets: [
        {
          id: "recent_search",
          label: "Recently",
          description: "Started this year",
          icon: "Calendar",
          options: ["this_semester", "last_semester"],
        },
        {
          id: "longer_or_not",
          label: "A while ago or not yet",
          description: "Been searching long or haven't started",
          icon: "History",
          options: ["over_a_year", "havent_started"],
        },
      ],
      options: [
        { id: "this_semester", label: "This semester", icon: "Calendar" },
        { id: "last_semester", label: "Last semester", icon: "CalendarDays" },
        { id: "over_a_year", label: "Over a year ago", icon: "History" },
        { id: "havent_started", label: "I haven't really started yet", icon: "Pause" },
      ],
    },
    {
      id: "follow_up_3",
      question: "Where have you been looking for opportunities? (select all that apply)",
      multiSelect: true,
      buckets: [
        {
          id: "online_platforms",
          label: "Online platforms",
          description: "Job boards and websites",
          icon: "Monitor",
          options: ["handshake", "linkedin", "company_sites"],
        },
        {
          id: "offline_or_none",
          label: "Offline or events",
          description: "Connections, fairs, or not started",
          icon: "Users",
          options: ["personal_network", "career_fairs", "havent_looked"],
        },
      ],
      options: [
        { id: "handshake", label: "Handshake", icon: "Monitor" },
        { id: "linkedin", label: "LinkedIn", icon: "Linkedin" },
        { id: "personal_network", label: "Family, friends, or personal connections", icon: "Users" },
        { id: "company_sites", label: "Company websites directly", icon: "Globe" },
        { id: "career_fairs", label: "Career fairs or employer events", icon: "Calendar" },
        { id: "havent_looked", label: "I haven't started looking yet", icon: "Search" },
      ],
    },
    {
      id: "follow_up_4",
      question: "What would help you most right now? (select all that apply)",
      multiSelect: true,
      buckets: [
        {
          id: "finding_opportunities",
          label: "Finding opportunities",
          description: "Targeting and materials",
          icon: "Target",
          options: ["know_where_to_apply", "stronger_resume"],
        },
        {
          id: "getting_support",
          label: "Getting support",
          description: "Practice, guidance, and time",
          icon: "MessageSquare",
          options: ["interview_practice", "someone_to_talk_to", "more_time"],
        },
      ],
      options: [
        { id: "know_where_to_apply", label: "Knowing exactly which companies to apply to for my major", icon: "Target" },
        { id: "stronger_resume", label: "Having a stronger resume or application", icon: "FileCheck" },
        { id: "interview_practice", label: "Getting real practice before interviews", icon: "Mic" },
        { id: "someone_to_talk_to", label: "Having someone walk me through the whole process", icon: "MessageSquare" },
        { id: "more_time", label: "Just having more time to focus on this", icon: "Clock" },
      ],
    },
    {
      id: "follow_up_5",
      question: "What's your major?",
      buckets: [
        {
          id: "quantitative",
          label: "Quantitative fields",
          description: "Numbers, data, and analysis",
          icon: "Calculator",
          options: ["finance", "accountancy", "business_analytics"],
        },
        {
          id: "applied_fields",
          label: "Applied and operational",
          description: "Marketing, operations, and more",
          icon: "Megaphone",
          options: ["marketing", "supply_chain", "other_major"],
        },
      ],
      options: [
        { id: "finance", label: "Finance", icon: "TrendingUp" },
        { id: "marketing", label: "Marketing", icon: "Megaphone" },
        { id: "accountancy", label: "Accountancy", icon: "Calculator" },
        { id: "supply_chain", label: "Supply Chain and Operations", icon: "Truck" },
        { id: "business_analytics", label: "Business Analytics", icon: "BarChart3" },
        { id: "other_major", label: "Other FSB major", icon: "GraduationCap" },
      ],
    },
  ],

  continuePrompts: [
    "That helps! Got one more in you?",
    "You're helping a lot! One more quick one?",
    "Almost done! One more?",
    "Last one, promise?",
  ],
};

export type Bucket = (typeof surveyConfig.buckets)[number];
export type PipelineStage = (typeof surveyConfig.pipelineStages)[number];
export type FollowUpQuestion = (typeof surveyConfig.followUpQuestions)[number];
